# Generated by Django 4.0.3 on 2022-09-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_salesrecord_automobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='is_sold',
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
