# Generated by Django 4.0.3 on 2022-09-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
